### ISSUE TITLE
Problem constructing BAM dataset

### ISSUE THREAD

**Issue by lisadunlap** [google-research-datasets/bim#6]
I am trying to construct this dataset with the scripts provided but I have run into problems with constructing the BAM dataset after downloading the models and COCO and MIniPlaces datasets. 

Why I run `python scripts/construct_bam_dataset.py` I get this:
~~~~
loading annotations into memory...
Done (t=11.94s)
creating index...
index created!
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
Traceback (most recent call last):
  File "scripts/construct_bam_dataset.py", line 379, in <module>
    paste_objects_to_scenes()
  File "scripts/construct_bam_dataset.py", line 151, in paste_objects_to_scenes
    'rb')).convert('RGBA')
  File "/Users/lisadunlap/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2808, in open
    im = _open_core(fp, filename, prefix)
  File "/Users/lisadunlap/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2790, in _open_core
    im = factory(fp, filename)
  File "/Users/lisadunlap/anaconda3/lib/python3.6/site-packages/PIL/ImageFile.py", line 106, in __init__
    self._open()
  File "/Users/lisadunlap/anaconda3/lib/python3.6/site-packages/PIL/PcdImagePlugin.py", line 40, in _open
    self.fp.seek(2048)
  File "/Users/lisadunlap/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/lisadunlap/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 179, in seek
    pywrap_tensorflow.Set_TF_Status_from_Status(status, ret_status)
  File "/Users/lisadunlap/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.OutOfRangeError: reached end of file
~~~~

I looked up the error but am not coming up with anything useful. Any ideas?

Thanks!

**Comment by lisadunlap** [comment]
Nvr mind, I got it!
